Create framework for OSPO Local Meetups
todogroup/ospology pull request #163
Opened 2022-07-21 08:20 UTC by anajsana

This framework defines the requirements to host and organize OSPO local meetups in local languages powered by TODO Group.

Signed-off-by: Ana Jimenez Santamaria <ana@todogroup.org>

2022-07-28 09:55 UTC, geekygirldawn requested changes
This looks great, thanks for doing this! I made mostly a few minor wording suggestions.

2022-07-28 09:55 UTC, geekygirldawn commented on local-meetups/framework.md
> +OSPOlogy is an initiative under the TODO group that offers best practice-sharing online workshops that are open to all, from folks starting their OSPOs to seasoned OPSOers! These sessions are typical
I think we should remove the hyphen between practice and sharing.

2022-07-28 09:55 UTC, geekygirldawn commented on local-meetups/framework.md
> +We are introducing a new framework for in-person local meetups. OSPO Local Meetups aim to provide a forum for like-minded professionals to share knowledge and experience on OSPOs and Open Source Mana
This is a duplicate of the sentence below in the introducing section.

2022-07-28 09:55 UTC, geekygirldawn commented on local-meetups/framework.md
> +* Encourages vendor-neutraly
should be neutrality

2022-07-28 09:55 UTC, geekygirldawn commented on local-meetups/framework.md
> +* Needs to have a Local TODO Organizer
This duplicates the second bullet.

2022-07-28 09:55 UTC, geekygirldawn commented on local-meetups/framework.md
> +OSPO Local meetups powered by the TODO Group is committed to vendor neutrality and aims to become a forum for like-minded professionals to share knowledge and experiences on OSPOs. Even though we und
Let's add a bit to this. Maybe something like what I proposed in Slack to add to or replace the part currently in bold:
Vendors may not propose solutions or use the meetups under the TODO Group umbrella for any discussions designed to generate sales for a vendor. Meetups are not intended to be vendor pitches and can’t be used for that purpose if you would like to have the meetup under the TODO Group branding.

2022-07-28 09:55 UTC, geekygirldawn commented on local-meetups/framework.md
> +* Providing meet-up location and logistics
I think we can remove this hyphen between meet and up

2022-07-28 09:55 UTC, geekygirldawn commented on local-meetups/framework.md
> +* Posting a recap to [OSPO Forum](https://github.com/todogroup/ospology/discussions/categories/announcements) in English language.
I'd remove the word language and just say "in English"

2022-07-28 09:55 UTC, geekygirldawn commented on local-meetups/framework.md
> +If you are interested in organizing a TODO Local Meetups in your region feel free to open a new [GH Discussion under OSPOlogy repo](https://github.com/todogroup/ospology/discussions), indicating the
Again, I'd remove the hyphen between meet and up

2022-07-28 10:59 UTC, anajsana commented
@geekygirldawn Thank you! committed changes with the requested additions 👍

2022-07-29 14:47 UTC, anajsana commented
Changes requested by the SC were added to the framework. Merging this PR to move forward. In case something else needs to be added or changed, please open a new PR.

2022-07-29 14:48 UTC, merged