Deduplicate content from 'Eliminate friction' section
todogroup/ospology pull request #186
Opened 2022-09-26 19:19 UTC by mfix22

IMO, the content under "Eliminate Friction from Using and Contributing to Open Source" is duplicated in other sections, most strongly in the InnerSource one. This PR distributes that content into the other sections.

I also removed "Continuously improve processes and tools to reduce learning curve and manual effort required" since it felt redundant—we already have 2 other sections on improving processes and policies, and other bullets on making contributing better or easier. 🙂 

What do you think @tsteenbe @anajsana?

2022-09-26 23:57 UTC, tsteenbe commented
@mfix22 Not in favor of this PR - "Eliminate Friction from Using and Contributing to Open Source" section is not about InnerSource at all. It's about making it easier for development organization to consume open source and contribute back upstream / start new OSS projects. InnerSource is a a practices focused within an organization.

Keep also in mind that mind map is meant to shows "what OSPO could do" which is why there is some duplication of items between points. Well aware of several OSPO that are not responsible for InnerSource but are tasked to make using and contributing to Open Source easier.

2022-09-27 00:02 UTC, tsteenbe requested changes

2022-09-27 00:02 UTC, tsteenbe commented on ospo-mindmap/Content/ospomindmap.md
> +  - Help navigate internal politics or policies
I do see how "Help navigate internal politics or policies" could be seen as sub point of "Improve collaboration across the organization" / InnerSource section. If we adding this as a subpoint I would prefer if we add another example else it look weird to me in the rendered mind map

2022-09-28 21:10 UTC, mfix22 commented
Makes sense @tsteenbe ! I just found this section to be overly redundant, when we have 2 other section specifically on using and contributing to open source. 

I attempted to reorganize this again. What do you think about this latest iteration? 

If you still disagree that this is worth doing, I will close this PR 🙂

2022-10-17 23:49 UTC, mfix22 commented
@tsteenbe any thoughts on the latest iteration here? If you still are not a fan, I'll close 🙂

2022-11-03 02:44 UTC, mfix22 commented
@tsteenbe just wanted to get your approval on the above before merging 🙂

2022-11-03 11:57 UTC, tsteenbe requested changes
I still prefer not to remove "Eliminate Friction from Using and Contributing to Open Source" - see value in it as a standalone responsibility.

2022-11-03 11:57 UTC, tsteenbe commented on ospo-mindmap/Content/ospomindmap.md
> +- Help navigate internal politics or policies
"Help navigate internal politics or policies" is not only a compliance topic but also a contributing to Open Source  - what if an engineer/product owner wants to open-source a big closed source application with several internal dependencies and approvals from multiple directories and above. OSPO is the team that can help with these kind of tasks that require existing relationships to higher management

2022-11-03 11:57 UTC, tsteenbe commented on ospo-mindmap/Content/ospomindmap.md
> +- Maintain relationships with communities of strategic importance to your organization
If we start elaborating the execution part of the strategy then "Maintain relationships..." should be a sub bullet under Open Source community, contributions and leadership

2022-11-15 04:43 UTC, mfix22 commented
Going to close this for now. Thanks for reviewing @tsteenbe.

2022-11-15 04:43 UTC, closed without merging