Final Review for chapter 4
todogroup/ospology pull request #500
Opened 2024-07-17 16:23 UTC by anajsana

Adding the changes that came from the final review during Chapter 4 meeting. During the call and the next two weeks, the changes were included using [this doc](https://github.com/todogroup/ospology/edit/main/ospo-book/content/en/04-chapter.md)for chapter intro and this doc for [activity table](https://drive.google.com/open?id=12wqqdCLgkTIor_onHvhCtLPE-Tsn44k2oWVxnisb6TM&authuser=0)

Contributors in this PR:

- Alice Sowerby
- Cornelius Schumacher
- Gergely Csatari
- Ana Jiménez

These people are already acknowledged in the OSPO Book contributors section.

Thank you!

2024-07-27 09:19 UTC, CsatariGergely requested changes

2024-07-27 09:19 UTC, CsatariGergely commented on ospo-book/content/en/04-chapter.md
> +| Open sourcing previously proprietary projects                               |                | Get the benefits of strategic involvement in and with open source
```suggestion
| Open sourcing previously proprietary projects                               | Build open source community leadership capabilities in the organization | Get the benefits of strategic involvement in and with open source                                                                                                           |
```

2024-07-27 09:19 UTC, CsatariGergely commented on ospo-book/content/en/04-chapter.md
> +| Establish an “upstream first” policy                                        |                | Lead open source projects and make them part of the primary value creation of the organization
```suggestion
| Establish an “upstream first” policy                                        | The OSPO can lean on the established leaders of the company open source projects               | Lead open source projects and make them part of the primary value creation of the organization                                                                              |
```

2024-07-27 09:19 UTC, CsatariGergely commented on ospo-book/content/en/04-chapter.md
> +| Supporting autonomy of contributors and maintainers of open source projects |                | Having people being dedicated to only open source work, the organization can strategically strengthen
```suggestion
| Supporting autonomy of contributors and maintainers of open source projects | Allows the scalability of open source leadership and creates "open source" champions in the company               | Having people being dedicated to only open source work, the organization can strategically strengthen important open source projects in the most organic and effective way. |
```

2024-07-27 09:19 UTC, CsatariGergely commented on ospo-book/content/en/04-chapter.md
> +> 2. Automation Security Checks: Implement automated security checks, such as the OpenSSF Security Scorecard, to continuously evaluate the security posture of projects. This proactive measure can hig
```suggestion
> 2. Automation Security Checks: Implement automated security checks, such as the [OpenSSF Scorecard](https://scorecard.dev/), to continuously evaluate the security posture of projects. This proactive measure can highlight vulnerabilities or anomalies that merit further investigation.
```

2024-07-27 09:19 UTC, CsatariGergely commented on ospo-book/content/en/04-chapter.md
> +> 1. Educational Initiatives on License Implications: Develop educational materials and sessions for developers and users within the organization to understand the nuances of different licenses. This
```suggestion
> 1. Educational Initiatives on License Implications: Develop educational materials and sessions for developers and users within the organization to understand the nuances of different licenses and open source governance models. This understanding will help them make informed decisions when using or contributing to open-source projects.
```

2024-08-06 18:32 UTC, alice-sowerby commented
@anajsana @CsatariGergely do you need anything from me / can I help in any way?

2024-08-16 14:09 UTC, alice-sowerby commented
Hi @anajsana @todogroup/book-reviewers , sorry for the delay in getting to review this. I have changed my notification settings so that hopefully I get notified when I am tagged :( 

I think this chapter needs a full copy edit and I can't get a the GH interface to let me do that in this PR. That could be my lack of experience. 

How would I go about getting the file from the branch to edit it?

2024-08-17 17:39 UTC, alice-sowerby commented
> Hi @anajsana @todogroup/book-reviewers , sorry for the delay in getting to review this. I have changed my notification settings so that hopefully I get notified when I am tagged :(
> 
> I think this chapter needs a full copy edit and I can't get a the GH interface to let me do that in this PR. That could be my lack of experience.
> 
> I will get a copy of the file from the branch to edit it and send back.

@anajsana I have edited a copy of the file locally, do you want me to create a PR?

2024-08-17 17:42 UTC, anajsana commented
> > Hi @anajsana @todogroup/book-reviewers , sorry for the delay in getting to review this. I have changed my notification settings so that hopefully I get notified when I am tagged :(
> 
> > 
> 
> > I think this chapter needs a full copy edit and I can't get a the GH interface to let me do that in this PR. That could be my lack of experience.
> 
> > 
> 
> > I will get a copy of the file from the branch to edit it and send back.
> 
> 
> 
> @anajsana I have edited a copy of the file locally, do you want me to create a PR?

Thank you @alice-sowerby ! If you could add the copy edit changes to this PR instead of creating a new one, it will be awesome. Just let me know if you need help!

2024-08-17 18:24 UTC, alice-sowerby commented
@anajsana I will see if I can figure out how to do it, and let you know if I hit any problems - thank you!

2024-09-02 06:40 UTC, anajsana commented
@alice-sowerby created a new PR with these changes + copy edits. See: https://github.com/todogroup/ospology/pull/503

Tag this as duplicated and Closing with no merge.

2024-09-02 06:40 UTC, closed without merging