Created Contribution.md
todogroup/ospology pull request #526
Opened 2024-12-06 03:35 UTC by harmonyelendu

To further facilitate participation and growth in OSS whitepaper the contribution.md file points contributors to the right direction by serving as a detailed guide in other to start contributing.

2024-12-06 07:05 UTC, anajsana commented
Thanks for starting this @harmonyelendu !

I assume you still need populate with content the Markdown created in this PR before is ready to be reviewed on my end. Please let me know once is finished 🙂

2024-12-07 04:30 UTC, harmonyelendu reviewed
@anajsana  added more context on my proposal for a contributor.md file for OSS in Business White Paper.

2024-12-07 08:10 UTC, anajsana requested changes
Thanks again for drafting the initial doc! I've made some suggestions to changes to the intro 🙂

2024-12-07 08:10 UTC, anajsana commented on whitepapers/business-value/Contribution.md
> +This is basically an Overview of what this document should entail.
```suggestion
This document provides an overview of the different ways individuals can contribute as co-creators of the whitepaper, as well as the different roles they can take on.
```

2024-12-07 08:10 UTC, anajsana commented on whitepapers/business-value/Contribution.md
> +The Contribution.md file will serve as a guide, providing the needed step by step process of how contributors will collaboratively work on the OSS in business whitepaper, ensuring collective approval
```suggestion
The Contribution.md file provides a step by step process of how contributors will work on the OSS in business whitepaper, ensuring collective approval from everyone invloved. Contributions can be organized into three groups:
```

2024-12-07 15:52 UTC, harmonyelendu commented
@anajsana Thanks so much for spotting better words

2024-12-18 16:00 UTC, anajsana requested changes
Thank you! requested a few changes. If you are ok with them, once merged into the branch, is good to go and this PR can be merged on my end

2024-12-18 16:00 UTC, anajsana commented on whitepapers/business-value/Contribution.md
> +- Group Lead: A group lead will be responsible for cordinating efforts and facilitating the progress of it's memebers. Group leads will serve beyond just guidance for the contributors as they work on
```suggestion
- Group Chair: A group chair will be responsible for coordinating efforts and facilitating the progress of the working group participants of each section. Group chairs will serve beyond just guidance for the contributors as they work on their respective sections before syncing through mini presentations during Touchpoint calls. However, individuals interested in becoming group chairs will have to meet set up basic requirements made by the working group before expressing their interest.  
```

2024-12-18 16:00 UTC, anajsana commented on whitepapers/business-value/Contribution.md
> +- Group members: Contributors will be organised into groups based off interest and expertise aligned with the topics and section provided through the outline in the whitepaper. Each group will be led
```suggestion
- Group participants: Contributors will be organised into groups based on interest and expertise aligned with the topics and section provided through the outline in the whitepaper. Each group will be led by a leader providing the required structure and ensuring accountability for progress.
```

2024-12-18 16:00 UTC, anajsana commented on whitepapers/business-value/Contribution.md
> +- The reviewer: This is a group of people that will focus more on reviewing the content of other contributors. Their role will ensure that all the work are well documented in google docs used for com
```suggestion
- Reviewer: This is a group of people that will focus more on reviewing the content of other contributors. Their role will ensure that all the work are well documented in google docs used for compling the contributions of all groups forming the whitepaper, while ensuring that the outlines and objectives of the working group for the whitepaper are maintained properly. The working group should make the google doc used for compilations public so viewers can also serve as reviewers through comments and suggestions which will be addressed in the meeting if they cannot be resolved within google docs. Later, the content should be moved into markdown format and added into this repo via Pull Request.
```

2024-12-18 16:00 UTC, anajsana commented on whitepapers/business-value/Contribution.md
> +Please note: I will be open for any questions and clarity if needed.
```suggestion
> Please note: I will be open for any questions and clarity if needed. 
```

2024-12-20 08:18 UTC, anajsana approved these changes

2024-12-20 08:18 UTC, merged