Update glossary.md
todogroup/ospology pull request #527
Opened 2024-12-06 03:51 UTC by harmonyelendu

2024-12-06 10:15 UTC, anajsana requested changes

2024-12-06 10:15 UTC, anajsana commented on whitepapers/business-value/glossary.md
> +TODO - Talk Openly, Develop Openly.
As this is not related to the content of the oss in business guide, I'd remove 🙂

2024-12-06 10:15 UTC, anajsana commented on whitepapers/business-value/glossary.md
> +Steering Committee - These are group of people that serve as a board of directors regulating and approving our activities here in TODO.
define SC as a general concept used in open source communities, not specific to TODO. Might be worth it to include "Board" and similar names used in communities / open source governance models

2024-12-07 15:44 UTC, harmonyelendu reviewed
All issues has been resolved.

2024-12-18 16:09 UTC, merged