Refine the top level README
todogroup/ospology pull request #80
Opened 2022-04-02 16:49 UTC by sdake

- clean up the language to use active voice
- remove conjunctions which may cause confusion
- add awesome emojis

Signed-off-by: Steven Dake <steven.dake@gmail.com>

2022-04-04 07:04 UTC, anajsana requested changes
This is great!! Thank you so much for contributing to making the README.md more appealing 💯 I've requested some changes in some of the sections and added comments between lines 🙂

2022-04-04 07:04 UTC, anajsana commented on README.md
TODO Community meetings structure changes a bit from what is has been described here, let me explain this better 🙂 They are structured into:

* [OSPOlogy community meetings](https://github.com/todogroup/ospology/tree/main/meetings#ospology-monthly-meetings): These are "General and public monthly meetings of the TODO Group and wider OSPO community, everyone is welcome to attend and participate". These meetings have always been a featured topic with special guests and the last 15 mins are reserved for community discussions. all these meetings are recorded, edited, and recorder on Youtube OSPOlogy Channel, so everyone across the globe can have access to it 👍 https://github.com/todogroup/ospology/tree/main/meetings#event-page-and-past-sessions

* TODO Chapters: These are location-based meetings and they do not follow the same structure as OSPOlogy community meetings. The community put topics of matter into an agenda and we have discussions the entire hour. We currently have [Europe Sync meetings](https://github.com/todogroup/ospology#todo-eu-chapter-sync-meetings-monthly) and [APAC Sync meetings](https://github.com/todogroup/ospology/discussions/67). Both are available in the community page calendar: https://todogroup.org/community/

2022-05-20 09:28 UTC, anajsana commented
Just reviewing opened PRs at ospology and checking their status. @sdake do you need help with this or is there anything I can help with? 🙂

2022-05-20 12:57 UTC, sdake commented
Ana,

I will finish this PR today. Thanks for the patience.

On Fri, May 20, 2022 at 2:29 AM Ana Jimenez Santamaria <
***@***.***> wrote:

> Just reviewing opened PRs at ospology and checking their status. @sdake
> <https://github.com/sdake> do you need help with this or is there
> anything I can help with? 🙂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/todogroup/ospology/pull/80#issuecomment-1132684575>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFYRCKXPOZ4ARIDDL5OBG3VK5LOHANCNFSM5SLFDMZA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-02 09:09 UTC, anajsana commented
> Ana, I will finish this PR today. Thanks for the patience.

@sdake are there any updates on this? 🙂

2022-06-02 14:26 UTC, sdake commented
Thanks, I have been a little busy with IRL. I will try to finish this easy
task up this week.

Cheers,
-steve

On Thu, Jun 2, 2022 at 2:09 AM Ana Jimenez Santamaria <
***@***.***> wrote:

> Ana, I will finish this PR today. Thanks for the patience.
>
> @sdake <https://github.com/sdake> are there any updates on this? 🙂
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/todogroup/ospology/pull/80#issuecomment-1144631445>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFYRCJRNYBRBCWJOHHRCDDVNB255ANCNFSM5SLFDMZA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-16 07:50 UTC, anajsana approved these changes

2022-06-16 07:54 UTC, anajsana commented
@sdake I committed to your branch the requested changes to the readme.md in order to move forward with this. However, there were a lot of previous changes made to the readme since you created this PR, and seems that this branch cannot be rebased due to conflicts.

2022-06-16 07:57 UTC, anajsana commented
Since this PR has not shown any activity over the past months, I'll create a new PR with the changes and mention this PR there.

2022-06-16 08:06 UTC, anajsana commented
Since this PR has not shown any activity over the past months, I'll create a new PR with the changes and mention this PR there https://github.com/todogroup/ospology/pull/136

2022-06-16 08:06 UTC, closed without merging

2022-06-16 12:32 UTC, sdake commented
Thanks @anajsana. I am attempting to find a new job, and I have been busy with a job hunt. Thank you for your understanding. I hope some of the ideas were useful. Also, nice job on adding netlify to the build system!

Cheers,
-steve